language: node_js
dist: focal
arch: amd64
cache: npm
addons:
  chrome: stable
os:
  - linux
  - osx
node_js:
  - 17
  - 16
  - 14
  - 12
install:
  - npm install
script:
  - npm run build
  - npm run test
