version: 2.1

orbs:
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test
      - store_test_results:
          path: ./coverage/junit-report.xml
      - store_artifacts:
          path: ./coverage/html-report
      - run:
          name: Build
          command: npm run build

workflows:
  test-and-build:
    jobs:
      - build
